baseURL = 'https://undacmic.github.io/'
languageCode = 'en-us'
title = '#undragos'
theme = 'base-theme'
enableEmoji = true
relativeURLs = true
[taxonomies]
  tag = 'tags'


[markup]
  defaultMarkdownHandler = 'goldmark'