baseURL = 'https://undacmic.github.io/undragos.me/'
languageCode = 'en-us'
title = '#undragos'
theme = 'base-theme'
enableEmoji = true

[taxonomies]
  tag = 'tags'


[markup]
  defaultMarkdownHandler = 'goldmark'